ATMsimulation/Controllers/CheckingAccountController.cs
using ATMsimulation.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace ATMsimulation.Controllers
{
    public class CheckingAccountController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: CheckingAccount
        public ActionResult Index()
        {
            return View();
        }

        // GET: CheckingAccount/Details
        public ActionResult Details()
        {
            var userId = User.Identity.GetUserId();
            var checkingAccount = db.CheckingAccounts.Where(c=>c.ApplicationUserId == userId).First();
            return View(checkingAccount);
        }

        [Authorize(Roles="Admin")]
        public ActionResult DetailsForAdmin(int id)
        {
            var checkingAccount = db.CheckingAccounts.Find(id);
            return View("Details", checkingAccount);
        }
        
        [Authorize(Roles="Admin")]
        public ActionResult List()
        {
            return View(db.CheckingAccounts.ToList());
        }

        public ActionResult Statement(int id)
        {
            var checkingAccount = db.CheckingAccounts.Find(id);
            return View(checkingAccount.Transactions.ToList());
        }

        // GET: CheckingAccount/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CheckingAccount/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ATMsimulation/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ATMsimulation.Models;
using Microsoft.AspNet.Identity;

namespace ATMsimulation.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        //GET /home/index
        [Authorize]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var checkingAccountId = db.CheckingAccounts.Where(c => c.ApplicationUserId == userId).First().Id;
            ViewBag.CheckingAccountId = checkingAccountId;
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.TheMessage = "Having trouble? Send us a message.";

            return View();
        }
        
        [HttpPost]
        public ActionResult Contact(string message)
        {
            //TODO : Send message to HQ
            ViewBag.TheMessage = "Thanks, we got your message!";
            return PartialView("_ContactThanks");
        }

        public ActionResult Serial(string letterCase)
        {
            var serial = "ASPNETMVC5ATM1";
            if(letterCase == "lower")
            {
                return Content(serial.ToLower());
            }
            return Content(serial);
        }
    }
}

ATMsimulation/Controllers/TransactionController.cs
using ATMsimulation.Models;
using ATMsimulation.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ATMsimulation.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private IApplicationDbContext db = new ApplicationDbContext();

        // GET: Transaction/Deposit
        public ActionResult Deposit(int checkingAccountId)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Deposit(Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                db.Transactions.Add(transaction);
                db.SaveChanges();
                var service = new CheckingAccountService(db);
                service.UpdateBalance(transaction.CheckingAccountId);
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public ActionResult Withdraw(int checkingAccountId)
        {
            ViewBag.InsuffMessage = "";
            return View();
        }

        [HttpPost]
        public ActionResult Withdraw(Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                var checkingAccount = db.CheckingAccounts.Find(transaction.CheckingAccountId);
                if (checkingAccount.Balance < transaction.Amount)
                {
                    ModelState.AddModelError("Amount", "You have insufficient funds!");
                }
                
                if(ModelState.IsValid)
                {
                    transaction.Amount *= -1;
                    db.Transactions.Add(transaction);
                    db.SaveChanges();

                    var service = new CheckingAccountService(db);
                    service.UpdateBalance(transaction.CheckingAccountId);
                    return RedirectToAction("Index", "Home");
                }
            }
            return View();
        }

        public ActionResult QuickCash100(int checkingAccountId, decimal amount)
        {
            var sourceCheckingAccount = db.CheckingAccounts.Find(checkingAccountId);
            var balance = sourceCheckingAccount.Balance;
            if(balance < amount)
            {
                return View("QuickCashInsufficientFunds");
            }
            db.Transactions.Add(new Transaction { CheckingAccountId = checkingAccountId, Amount = -amount });
            db.SaveChanges();

            var service = new CheckingAccountService(db);
            service.UpdateBalance(checkingAccountId);

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Transfer(int checkingAccountId)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Transfer(TransferViewModel transfer)
        {
            //check for available funds
            var sourceCheckingAccount = db.CheckingAccounts.Find(transfer.CheckingAccountId);
            if(sourceCheckingAccount.Balance < transfer.Amount)
            {
                ModelState.AddModelError("Amount", "You have insufficient funds!");
            }

            //check for a valid destination account
            var destinationCheckingAccount = db.CheckingAccounts.Where(c => c.AccountNumber == transfer.DestinationCheckingAccountNumber).FirstOrDefault();
            if(destinationCheckingAccount == null)
            {
                ModelState.AddModelError("DestinationCheckingAccountNumber", "Invalid destination account number.");
            }

            //add debit/credit transactions and update account balances
            if(ModelState.IsValid)
            {
                db.Transactions.Add(new Transaction { CheckingAccountId = transfer.CheckingAccountId, Amount = -transfer.Amount });
                db.Transactions.Add(new Transaction { CheckingAccountId = destinationCheckingAccount.Id, Amount = transfer.Amount });
                db.SaveChanges();

                var service = new CheckingAccountService(db);
                service.UpdateBalance(transfer.CheckingAccountId);
                service.UpdateBalance(destinationCheckingAccount.Id);

                return PartialView("_TransferSuccess", transfer);
            }
            return PartialView("_TransferForm");
        }

    }
}

ATMsimulation/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title Midwestern Vista Community Bank</h2>

<p>
    Thank you for checking out my bank app, I appreciate your time. Feel free to use any fictional email to
    create an account and explore: bob@something.com and variations of will work just fine.

    To use the transfer funds feature, i suggest creating two accounts as you'll need the account number in 
    order to be able to transfer funds to it.

    My contact information is on the contact page if you'd like to reach out to me with opportunities.
</p>

<div class="small">
    Disclaimer: This is a fictional "bank" created for the sole purpose of providing proof of coding knowledge
    using the MVC ASP.Net framework. Any funds "deposited" are fictional numbers being added to a SQL database.
    No withdrawls are to be made with the expectation to receive real currency.
</div>

ATMsimulation/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<h2>@ViewBag.Title.</h2>


<address>
    Joshua Beaty<br />
    Wichita Falls, TX, 76308<br />
    <span class="fa fa-phone"></span> 214-609-2537<br />
    <span class="fa fa-envelope"></span><a href="mailto:joshua.a.beaty@gmail.com"> joshua.a.beaty@gmail.com</a><br />
</address>

<div id="formSection">
    <h3>@ViewBag.TheMessage</h3>
    <small>This doesn't send anywhere.</small>
    <form method="post" id="contactForm">
        <div><textarea name="message" id="message" maxlength="150" data-bind="value:message,valueUpdate:'input'"></textarea></div>
        <div class="small"><span data-bind="text:charactersRemaining "></span> characters remaining</div>
        <div><input type="submit" value="Send" /></div>
    </form>
    <img src="~/Content/Images/ProgressIcon.gif" id="progress" style="display:none;" sizes="50px" />
</div>

@section scripts
{
    <script src="~/Scripts/knockout-3.5.1.js"></script>
    <script>
        function ContactViewModel() {
            var self = this;
            self.message = ko.observable('');
            self.charactersRemaining = ko.computed(function () {
                return 150 - self.message().length;
            });
        }
        ko.applyBindings(new ContactViewModel());
    </script>

    <script>
        $('#contactForm').submit(function () {
            $('#progress').show();
            $.post('', { message: $('#message').val() })
                .done(function (response) {
                    setTimeout(function () { $('#formSection').html(response); }, 1000);
                });
            return false;
        });
    </script>
}

ATMsimulation/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}



<div class="row">
    <div class="col-md-6 margin-top-20">
        <a href="@Url.Action("Withdraw", "Transaction", new {checkingAccountId = ViewBag.CheckingAccountId})" class="btn btn-primary btn-lg btn-block">
            <span class="fa fa-arrow-circle-down"></span>
            Withdrawl
        </a>
        <a href="@Url.Action("QuickCash100", "Transaction", new { checkingAccountId = ViewBag.CheckingAccountId, amount = 100 })" class="btn btn-primary btn-lg btn-block">
            <span class="fa fa-bolt"></span>
            Quick Cash $100
        </a>
        <a href="@Url.Action("Details", "CheckingAccount")" class="btn btn-primary btn-lg btn-block">
            <span class="fa fa-question-circle"></span>
            Balance Inquiry
        </a>
        @ViewBag.InsuffMessage
    </div>
    <div class="col-md-6 margin-top-20">
        <a href="@Url.Action("Statement", "CheckingAccount", new { id = ViewBag.CheckingAccountId })" class="btn btn-primary btn-lg btn-block">
            <span class="fa fa-print"></span>
            Print Statement
        </a>
        <a href="@Url.Action("Transfer", "Transaction", new { checkingAccountId = ViewBag.CheckingAccountId })" class="btn btn-primary btn-lg btn-block">
            <span class="fa fa-exchange-alt"></span>
            Transfer Funds
        </a>
        <a href="@Url.Action("Deposit", "Transaction", new {checkingAccountId = ViewBag.CheckingAccountId})" class="btn btn-primary btn-lg btn-block">
            <span class="fa fa-arrow-circle-up"></span>
            Deposit
        </a>
    </div>
</div>

ATMsimulation/Views/Home/_ContactThanks.cshtml
<h3>@ViewBag.TheMessage</h3>